### ISSUE TITLE
Update API to 2.8.1e (add phone number verification)

### ISSUE THREAD

**Issue by soren121** [soren121/yodel#100]
Yik Yak pushed a new update today (7/15) that implements new anti-spam features. To push adoption, they're disabling mutable actions (i.e. posting, voting) on 7/19 for all older clients. This includes Yodel, since it mimics the previous version of their Android app.

A new update will be out soon that's compatible with Yik Yak's changes. Hold in there!

**Comment by SuperSpyTX** [comment]
R.I.P Anonymity

**Comment by soren121** [comment]
I know right 😒

**Comment by SuperSpyTX** [comment]
It would've been easier for them to implement CAPTCHA instead of phone numbers and affect anonymity.

**Comment by soren121** [comment]
Strongly agreed. But obviously, calling it "spam protection" was a cover. They realized what they created was more harmful than Reddit, and they wanted users' identities so they could easily report illegal activity and cover their asses legally. Spam & bots can be caught with heuristics and CAPTCHA's, like you said.

Sent from my Windows Phone

-----Original Message-----
