### ISSUE TITLE
Verification error + no opaque tile

### ISSUE THREAD

**Issue by spencejah** [soren121/yodel#103]
![wp_ss_20150721_0001](https://cloud.githubusercontent.com/assets/9154645/8820702/9177ea2a-2ff3-11e5-8ced-6c663ff4c4a7.png)

I enabled the "opaque tile" option but it didn't work. Tried re-pinning the tile and doing a soft reset but still didn't work. Perhaps re-installing the app might work but I'm not really willing to try cause of that oh so sweet sweet Yakarma. lol
Also, when i tried verifying my phone to post a Yak, I got the text, entered the code in, but got this error message each time.

**Comment by pi99y** [comment]
I can confirm the verification error.

**Comment by soren121** [comment]
Either Yik Yak's verification isn't working right now or I did something very wrong. It worked fine last time I tried it...

I'll check it out shortly.

**Comment by soren121** [comment]
Well, crap. I just tried it again in the emulator and it worked fine. I don't know what's wrong.

Would either of you be open to doing some mildly complicated debugging? I can walk you through it, but you'll need a PC and you'll need to be on your home WiFi. It would probably take 10-15 minutes.

Also, @spencejah, are you exiting the settings page (via the back button) before checking the tile? The checkbox won't save until you leave settings.

**Comment by pi99y** [comment]
Hi, I was able to go trough verification process just fine hours later so it might have been on the YikYak's side...

I can do some debugging if it helps, but not sooner than 11 hours from now.
I'll check here tommorow aroud 8-9am CET.

**Comment by soren121** [comment]
Yes, others have reported that trying it again works...but I'd still like to know why it's failing the first time. I'm going to see what I can do about it tonight and report back before Thursday morning.

**Comment by pi99y** [comment]
Some additional info: When it didn't work I tried it several times and YikYak always gave (SMS) me the same verification code number, when I tried again later (and it worked) the code was different. This could be just how it works and is not related...

**Comment by soren121** [comment]
No, it's definitely supposed to work the first time. It always does for me, whether I use the official Android app or Yodel. This is a bug.

Thanks for the info though, I appreciate it.

**Comment by soren121** [comment]
Good news! I managed to trigger the error you're all getting. A fix will be out by Thursday morning.

**Comment by soren121** [comment]
The update that fixes the verification bugs, 1.4.1.1, is live in the Store. Try it out!
