### ISSUE TITLE
herd top yaks

### ISSUE THREAD

**Issue by tiscott1** [soren121/yodel#104]
Not sure if this is intended functionality or not, but when I'm in my herd and hit top yaks, I get top yaks in my area rather than top yaks in my herd.

**Comment by soren121** [comment]
It honestly slipped my mind to look at that. Let me check and see if the official app shows you Top Yaks while in your herd.

**Comment by soren121** [comment]
Apologies for the delay...I wiped my PC and installed Windows 10 the other day, and it took a while to get my Android emulator up and running again.

It looks like Top Yaks in My Area doesn't use your My Herd location in the official apps-- that is to say, it always shows your local yaks.

I agree that this is a little confusing...I think the right course of action here would be to hide the "Top Yaks" link while you have My Herd turned on. What do you think?

**Comment by tiscott1** [comment]
Yeah, I think that's a solid solution. Alternatively, you could sort the yak list by score if that's your cup of tea.
