### ISSUE TITLE
Viewing other places (add peek anywhere)

### ISSUE THREAD

**Issue by user11223** [soren121/yodel#38]
The list of colleges or places is getting smaller. The iPhone version of Yik yak has a greater  list. I would like to be able to see the neighboring college's yaks or just any other yaks from other schools.I also can't see top yaks from my location.
Not a big deal. It would just be a nice feature to have on this app.

**Comment by dbeck21** [comment]
wait, so in the 1.0 update, are you adding a feature where we can search/ save places we want to peek from? like the iphone app

**Comment by soren121** [comment]
Yes, that's right. Whether or not it will make the 1.0 release, I'm not sure yet.

**Comment by dbeck21** [comment]
Ok thank you

-----Original Message-----

**Comment by pi99y** [comment]
I'd really like to see ~"peek anywhere" or something similar since there's not much Yak activity in my area... Please prioritize this or a similar feature. Thanks.
