### ISSUE TITLE
Dark theme / accent color

### ISSUE THREAD

**Issue by EliminatorZigma** [soren121/yodel#6]
Just another cosmetic suggestion. I know people can get tired of such a bright color scheme after a while, so a dark theme might be useful. Accent colors are really optional, I just always find it a nice touch on a lot of third-party apps.

If you're concerned with implementation, I know a few apps that require the app to be closed and opened again for color schemes to work, so don't worry if that's the best way you can find to implement this.

**Comment by soren121** [comment]
Surprise!

![wp_ss_20150320_0002](https://cloud.githubusercontent.com/assets/295939/6757118/f7241a92-cf04-11e4-91cc-3b101c9135a3.png)

**Comment by clevbolt** [comment]
Awesome!

-----Original Message-----

**Comment by soren121** [comment]
Theme & accent support is pretty much done as of today. There'll be an update available either tonight or tomorrow afternoon.
