### ISSUE TITLE
Yodel

### ISSUE THREAD

**Issue by clevbolt** [soren121/yodel#60]
How's the beta coming along? Haven't heard about anything in a while. Still working on it? What's next?

**Comment by soren121** [comment]
Good news is, I picked up development again a week ago...then I immediately got sick. But now that I'm getting over that, there'll be a new update coming in the next few days. Sorting is finally being added, as well as featured peek feeds. Also, various bugs will be fixed, including #50, #56, and #42. Plus a "dev news" feature (#26) that keeps everyone up-to-date on any breakages, i.e. if Yik Yak changed something on their side that broke Yodel. And crash reporting, although that's really of no use to you guys.

Unfortunately, I can't promise a fix for #37 at the moment.

**Comment by clevbolt** [comment]
You've made a lot of progress. Keep up the good work!

-----Original Message-----

**Comment by clevbolt** [comment]
When are you planning on releasing the next update?

**Comment by Yarach** [comment]
Hey man, I really appreciate the work. I would like to join the beta program as YikYak is not very popular here in the Netherlands yet. But a friend of mine and me want to make it more popular. Could I get permission to join the beta download?

**Comment by soren121** [comment]
I just submitted a new update (0.9.4.0), it adds featured peek feeds and fixes #50, #56, and #61. Because this is an emergency update, sorting and the fix for #37 didn't make it in, as they're not *quite* finished, but I'm aiming for another release on Valentine's Day. Because I love you guys!

**Comment by jesy99** [comment]
Thank you, it works!!! Its a Valentines Day miracle!!!!
