### ISSUE TITLE
Can't load the app

### ISSUE THREAD

**Issue by nayru-** [soren121/yodel#61]
Haven't been able to open the app today. Get this error message for a brief second and then everything crashes.
![wp_ss_20150211_0001](https://cloud.githubusercontent.com/assets/10968096/6159430/503890e4-b223-11e4-9fa0-d50eb2bbc33a.jpg)

**Comment by Haddaddy** [comment]
I've been getting the same thing

Sent from my Windows Phone
________________________________

**Comment by soren121** [comment]
Yik Yak is down. The official app is having the same issue right now, but it handles it a little more gracefully, as you can see:

![capture](https://cloud.githubusercontent.com/assets/295939/6159473/000aa9d0-b224-11e4-9957-58931f7a16ef.PNG)

**Comment by soren121** [comment]
I'll keep this issue open until they fix things on their side, just so people don't create duplicate issues.

**Comment by jesy99** [comment]
Is the original app still down because I haven't heard anything from anybody with it?

**Comment by soren121** [comment]
As far as I know, yes. My Android emulator is still giving 500 errors. I asked their Twitter support page but I haven't gotten an answer back yet.

**Comment by jesy99** [comment]
OK, thanks. If you do hear back from them could you share what they say?

**Comment by soren121** [comment]
Sure thing.

**Comment by soren121** [comment]
Yik Yak decided to suddenly start rejecting the user-agent I use. This broke Yodel, as well as the Android emulator I was using, which used the same user-agent. I've fixed it and I'm pushing an emergency release with the fix included.

**Comment by jesy99** [comment]
Will that automatically fix the app thats on my phone or will I have to do anything for the app to work?

**Comment by soren121** [comment]
The update will fix it automatically.

**Comment by jesy99** [comment]
Ok, thank so much! How long do you think it will take to fix?

**Comment by soren121** [comment]
The update will be available within the next two hours.

**Comment by teetz** [comment]
Got the update, and it worked for a bit but its giving me the 500 error again, but unlike before it stays on the splash screen instead of closing. Any ideas? Could this just be on my end? I've tried restarting my phone, reinstalling, and over wi-fi and cellular.
