### ISSUE TITLE
500 server crash after update

### ISSUE THREAD

**Issue by harlequinzeg0** [soren121/yodel#62]
I'm still receiving the 500 crash after the .9.4.0 update you just put out to fix it :/

**Comment by teetz** [comment]
Same here. For me, instead of crashing immediately like it did yesterday, it just sits on the splash screen.

**Comment by harlequinzeg0** [comment]
Important to note the message is now "unable to register new user" instead of being unable to load the feed.

**Comment by soren121** [comment]
I promise you, it worked last night. Yik Yak broke it again.

If they want to play hardball, I can play...

**Comment by soren121** [comment]
I just submitted version 0.9.4.1 to fix this. It should be available in the Store within the next two hours.

**Comment by soren121** [comment]
Just a note, I noticed a mistake in the update and I had to unpublish it. A fixed version will be available around 3:30pm EST. Sorry for the inconvenience!
