### ISSUE TITLE
Posts No Longer Loading

### ISSUE THREAD

**Issue by jesy99** [soren121/yodel#63]
Thank so much for all your hard work the last few days. My app is back and running except for now i can't post anything. The screen just keeps loading but it never posts:(

**Comment by jesy99** [comment]
P.S. Reading that the thank you part sounds really sarcastic but its not!

**Comment by soren121** [comment]
Sorry to hear that. Can you try uninstalling and reinstalling the app?

**Comment by jesy99** [comment]
Sure!

**Comment by jesy99** [comment]
If I do that should I expect to loose my yak karma  and older posts?

**Comment by soren121** [comment]
No, those shouldn't go away.

**Comment by jesy99** [comment]
Ok, thanks!

**Comment by EdGrimley** [comment]
Just FYI. I un-installed and re-installed, and I no longer get the 500 error. Thanks :+1:

**Comment by soren121** [comment]
@jesy99 And what about you? Did uninstalling and reinstalling work?

**Comment by jesy99** [comment]
Yes, it worked! Thanks

**Comment by soren121** [comment]
:D
