### ISSUE TITLE
update

### ISSUE THREAD

**Issue by clevbolt** [soren121/yodel#65]
The email said the update was released, but it isn't available yet? Also. Good luck in the app store! Glad to see all the progress and the long way this app has come

**Comment by soren121** [comment]
I submitted it, but it takes some time before it appears in the Store. Give it a couple hours.

Sent from my Windows Phone

-----Original Message-----

**Comment by clevbolt** [comment]
Updated it. It looks very good! Works well as far as I know. 5 stars!

**Comment by BlueIsTheColour** [comment]
I just have a suggestion for the logo. It has too much white space. I understand the minimal look, but nothing about it looks heavy. It feels very thin.

**Comment by soren121** [comment]
Icon design really isn't my forte. I've been thinking about re-doing it.
