### ISSUE TITLE
issues if i relaunch/open the app

### ISSUE THREAD

**Issue by hofes** [soren121/yodel#67]
In case I open the app (again) the field where the comments should occur are staying empty and i have to open the app again. in this case the comments never refresh and i have to do it manually.

**Comment by hofes** [comment]
the last update fixed that? i have no loading feed issue anymore and it gets updated when i open the app again

**Comment by soren121** [comment]
It did? Huh. I only noticed it happening with the "nearby" feed on the home screen. Didn't notice it happening with comments. But I suppose it's possible that I fixed that too. Thanks for reporting back!
