### ISSUE TITLE
Constant Threatening Language Warning 

### ISSUE THREAD

**Issue by drewfitzy** [soren121/yodel#68]
For every yak that I post I get the "Hold on a second!" warning saying that my post might contain threatening language and then I have to confirm that it does not actually contain threatening language. None of my posts are threatening or offensive so it doesn't make sense; there is obviously a glitch somewhere.

**Comment by soren121** [comment]
Just to be sure, this is the threatening words list: https://gist.github.com/soren121/a321f684b7516afff050

Are you positive you aren't using any of the words on that list? And if possible, could you post some samples of yaks you've been trying to submit, so I can test it?

**Comment by drewfitzy** [comment]
yeah i am sure, for instance I just posted a yak "Hello darkness my old friend." to test it, and it came up with the warning.

**Comment by soren121** [comment]
Ha, okay. I'll look into it later today.

**Comment by drewfitzy** [comment]
yeah, its no big deal, it's still letting me post, it is just kind of annoying to have to keep telling it that there isn't any threatening language.

**Comment by soren121** [comment]
I think I've fixed it. I couldn't replicate your problem, but I did fix some issues in the threat override code and it shouldn't happen again.

I'll release an update later today with the fix.

**Comment by drewfitzy** [comment]
Ok awesome thanks. It stopped happening shortly after I reported it, so I don't know what caused it.

-----Original Message-----
