### ISSUE TITLE
id transfer problem

### ISSUE THREAD

**Issue by max128** [soren121/yodel#77]
Dear soren121,

Thank You so much for this app! I love it.
I try to transfer my id to the public version of the app but get the notification "unable to decrypt id. Something's fishy here."

I think I did everything right, tried it different times today. I would be really sad if I loose my yak karma :( any tips or hints for me?

Thank you very much.

**Comment by soren121** [comment]
Fixed in 10168a5. I pushed a new update to the Store just now, version 1.1.0.2. Hopefully it should fix your problem. The update should be available in the next few hours.

If you've updated and it's still broken, please reopen this issue.

**Comment by max128** [comment]
Works now. Thank you so much. Incredibly fast response!
