### ISSUE TITLE
Handle Problems

### ISSUE THREAD

**Issue by jesy99** [soren121/yodel#78]
Hey! I just started experiencing some problems with handles on my yaks that I would assume can be attributed to a recent update that yodel received. I added a handle earlier in the day and now whether I press on or off on the new on/off handle toggle, I still get a handle. Every time I yak then, I have to turn the handle on, delete it, turn it off, and then post the yak. Thanks!

**Comment by soren121** [comment]
I probably should've tested the handle feature again after I changed the toggle. Grr.

I'll look into it tomorrow.

**Comment by soren121** [comment]
I just pushed another update, version 1.1.0.3, to fix this. It should be available on the Store in the next few hours. Thanks for reporting this!
