### ISSUE TITLE
yaks being deleted/no new feed

### ISSUE THREAD

**Issue by breakitbobby** [soren121/yodel#79]
I have had several of my yaks deleted only moments after being posted. I don't get new feed and can't see yaks my friends just recently posted. Idk where you get the positive reviews from but this isn't in my opinion a good app.

**Comment by soren121** [comment]
Uh...*okay*. Obviously you are in the minority of people having issues like this.

Please answer these troubleshooting questions so I can help: 

1. How long have you been using the app?
2. Have you always had these problems with the app?
3. If you don't mind answering, where are you using the app?

**Comment by breakitbobby** [comment]
I have no issue answering these question. 

1. I've been using the app since this past Monday. 

2.these problems have occurred since Monday. And I did install the update today as well but yet my yaks still get deleted. 

3. I'm using it near my local college campus. And I know people frequently update because I used yik yak on my iPhone and it constantly had updates.

-----Original Message-----

**Comment by soren121** [comment]
Try uninstalling and reinstalling the app, and if that doesn't solve your issue, reset your user ID using the button in the app's settings page.

Sent from my Windows Phone

-----Original Message-----

**Comment by breakitbobby** [comment]
I had thought of that and it still didn't work. I did that yesterday and my problems still persist.

-----Original Message-----

**Comment by vanamee** [comment]
I used to have this problem too, but it mysteriously went away after about a week after I first got the beta. I think a lot of folks had the same experience... Just give it another few days to see, and keep trying. Good luck!

Sent from my Windows Telephone

-----Original Message-----

**Comment by breakitbobby** [comment]
Well I will keep the app but if things don't improve I will let it be known. I'm not trying to hate on the app, I am glad its here but I just want it to work. Now all we need is a snap chat app and things will be good.

-----Original Message-----

**Comment by soren121** [comment]
It may require a code change, although I'm not sure what the problem is yet. I've never encountered this issue myself.

@vanamee: This is likely a different issue than the one that plagued the beta for so long.
