### ISSUE TITLE
Crash when viewing full threads

### ISSUE THREAD

**Issue by pjsummersjr** [soren121/yodel#80]
The app keeps crashing when I drill into a thread. 

Lumia Icon, Denim update.

**Comment by soren121** [comment]
I bet this is only happening when the app resumes back to a comment thread, right?

**Comment by pjsummersjr** [comment]
No. It occurred a few times when initially opening the full thread. I opened it, saw it flash and then the app crashed.

-----Original Message-----

**Comment by soren121** [comment]
Okay, I just managed to reproduce that bug. I'll have it fixed in a few hours.

Sent from my Windows Phone

-----Original Message-----

**Comment by soren121** [comment]
Aaaaaand I haven't been able to reproduce it while attached to the debugger. Argh! I'll get it eventually.

How long have you been using Yodel? Did it crash before the most recent update, v1.1.1.0 from last Wednesday?

**Comment by pjsummersjr** [comment]
Just installed it over the weekend. Haven't been using it a ton but this bug popped up pretty quickly.

-----Original Message-----

**Comment by soren121** [comment]
To help identify the issue, I added crash reporting to the app. You'll get an update in a couple hours that has this feature. Hopefully it'll help me figure out what's going on here!

**Comment by soren121** [comment]
There's a new update out, v1.1.1.3, that should fix this particular crash permanently. Can you test it out and report back in a day or so?

**Comment by pjsummersjr** [comment]
It hasn't come through yet but I'll start playing with it again once it does.

-----Original Message-----

**Comment by pjsummersjr** [comment]
I got a couple of crashes this morning … but I was in the car and I think the network might have been spotty. I was actually just resuming the app, not necessarily going into a thread.






Sent from Windows Mail





From: Paul Sr
Sent: ‎Tuesday‎, ‎March‎ ‎31‎, ‎2015 ‎8‎:‎51‎ ‎PM
To: soren121/yodel






It hasn't come through yet but I'll start playing with it again once it does.

**Comment by soren121** [comment]
Resume crashes are a separate thing that I'll be fixing today. I'm 99.99% sure I've fixed the particular crash that this report pertains to, though.
