### ISSUE TITLE
Cannot view full title

### ISSUE THREAD

**Issue by clevbolt** [soren121/yodel#82]
For example when viewing featured, I cannot see exactly what the poll question or category if it exceeds the amount of characters in the viewing area before going off the screen. Not a big deal, just something to eventually work on

**Comment by clevbolt** [comment]
Nevermind.

**Comment by soren121** [comment]
You mean in the peek list?

If you click on it, then you can scroll the title in the header. A horizontal scroll bar will appear for a second to indicate that you can do that.

Sent from my Windows Phone

-----Original Message-----

**Comment by soren121** [comment]
:)
