### ISSUE TITLE
This app only works on WiFi. 

### ISSUE THREAD

**Issue by JohnIvory** [soren121/yodel#85]
I'm not sure if this is a problem specific to my phone, but whenever I try to run your app with my data connection I get the following error: "Unable to load feed. HTTP Error 500 Internal Server Error".

Is this expected behaviour?

**Comment by soren121** [comment]
Certainly not. It should work on any type of connection.

That's so bizarre. And it works fine on WiFi, you say?

**Comment by JohnIvory** [comment]
Yup. I only noticed the problem when I was between networks and tried to load it up. To confirm I disabled WiFi when I was back home and the same error message showed up.

**Comment by soren121** [comment]
Well...I know that they've banned some IP addresses; perhaps they've done that a bit overzealously. That's my only guess as to what happened here. Theoretically, if you had an iPhone or an Android phone, it'd still be broken, but there's not really a way to test that.

I wish I could help, but there's nothing I can do here.

**Comment by JohnIvory** [comment]
Alright. Thanks

**Comment by Haddaddy** [comment]
I believe I am having the same issue
