### ISSUE TITLE
Empty Yak Page

### ISSUE THREAD

**Issue by willit37** [soren121/yodel#86]
I have an HTC One M8 with WP8.1 and have been having numerous issues with the app recently. Most of the time it wont load a page and when it does, it's empty. Zero yaks on UConn campus isn't really possible. Not sure what the issue is. Most times that I open the app it won't work, only about 10% of the time will yaks load.

**Comment by soren121** [comment]
First off, sorry for the delayed response. I haven't seen this issue before. Let me look into it.

**Comment by soren121** [comment]
This is crazy late, but I think I've finally fixed this. Update to version 1.4.2.0 and reset your ID.

If you don't use Yodel anymore, it's not a big deal. I'd just like to mark this issue as fixed.
