### ISSUE TITLE
Icons in threads for user differentiation 

### ISSUE THREAD

**Issue by guateke** [soren121/yodel#87]
Recent official app update added the use of icons in threads where each commenter is assigned an icon to differentiate between the original poster and other commenters.

**Comment by guateke** [comment]
Awesome job btw :)

**Comment by soren121** [comment]
Hm, interesting. I'll look into adding this. Shouldn't be too hard.

And thank you!

**Comment by soren121** [comment]
I've added this feature just now to the repository. It'll show up in an update either today or tomorrow.

**Comment by guateke** [comment]
Great!
________________________________
