### ISSUE TITLE
close to a school

### ISSUE THREAD

**Issue by jbmoore3** [soren121/yodel#88]
I keep getting messages that I'm too close to a school and that Yik Yak is for adults only. I can no longer view the feed nor post yaks nor replies

**Comment by soren121** [comment]
Well, assuming you are not actually close to a K-12 school, have you tried closing the app in the multitasking list and then reopening it to refresh your location?

If you *are* close to a school, then I can't (and won't) help.

**Comment by jbmoore3** [comment]
I live 6 blocks from a school. But I was getting the same error even when I'm no where near the school.

**Comment by soren121** [comment]
And does force-quitting the app and re-opening it help, when you're nowhere near the school?
