### ISSUE TITLE
can't access recent yaks/recept replies

### ISSUE THREAD

**Issue by tiscott1** [soren121/yodel#90]
Whenever I go to access recent yaks or replies, I get a list of the yaks, but when I click on them, the app doesn't open the comments. I'm still given the ability to scroll through the feed, but no other navigation works.

**Comment by soren121** [comment]
I actually fixed this earlier this morning, but for some reason Microsoft is taking their sweet time in publishing the update. I'll post another comment when the update gets through.

Sent from my Windows Phone

-----Original Message-----

**Comment by soren121** [comment]
The update is finally live in the Store. [Download it here.](https://www.windowsphone.com/en-us/store/app/yodel/9b3e9c28-18cc-460b-9c83-b3d44d62dc83)
