### ISSUE TITLE
My Recent Yaks/Replies Bug

### ISSUE THREAD

**Issue by spencejah** [soren121/yodel#91]
Yeah the new update today broke my Yodel (April 21). When I move over to he user settings and click on either My Recent Yaks or My Recent Replies and I click on any Yak, it just sends me to the My Recent Replies page and is stuck there.

**Comment by soren121** [comment]
Using 1.2.1.1 or 1.2.1.2?

Sent from my Windows Phone

-----Original Message-----

**Comment by spencejah** [comment]
Okay, yeah. I just updated it again and now it's working. Thanks.

**Comment by soren121** [comment]
You're welcome! Not sure how I let this one slip by in the first place.
