### ISSUE TITLE
suggestion: basecamp

### ISSUE THREAD

**Issue by max128** [soren121/yodel#93]
Yik Yak introduced The basecamp feature yesterday. It allows to set one place where you can see yaks, post and vote no matter where you actually are.
As I'm an international student returning to a place without yaks soon, this would be awesome to have.
Thanks for all of your work, this is one of my favorite apps.
Cheers
Max

**Comment by soren121** [comment]
I've had a similar feature planned for awhile but I haven't had a chance to implement it yet.

I'll add Basecamp support after doing notifications & peek anywhere. I'd expect it to arrive in May.

**Comment by max128** [comment]
Awesome! Looking forward :) Good luck on finals!
