### ISSUE TITLE
No yaks to speak of when using data 

### ISSUE THREAD

**Issue by Haddaddy** [soren121/yodel#95]
When I'm running the app on my data I don't have a feed or yakarma but when I turn on my Wi-Fi I am connected and have a feed, my yakarma, recent yaks, recent replies, etc. Not sure what the issue is. The app has worked well in the past.

**Comment by soren121** [comment]
As far as I know, this is a Yik Yak issue and there's nothing I can do about it. If that changes, I'll be sure to let you know.
