### ISSUE TITLE
Refresh location periodically

### ISSUE THREAD

**Issue by kellassidy** [soren121/yodel#96]
I visited lake county 4 days ago (yik yak population = 2) and I'm still seeing and posting in the Lake County yik yak page even though I'm 3 hours away from there. There's a crazy slow turn around time

**Comment by soren121** [comment]
Close the app in the task list and re-open it. Right now it only refreshes your location when you start the app fresh.

**Comment by kellassidy** [comment]
Closing the task from my phone didn't work, but turning my phone off and on again did.

**Comment by PatrickMurphy** [comment]
I think the way apps like 6tin use a button in settings to manually update position now if you want to is a good solution as well as whatever you had planned soren121

**Comment by soren121** [comment]
Tinder has a much wider radius than Yik Yak does (I think the smallest possible radius on Tinder is 10mi, whereas Yik Yak is locked to ~2.5mi.) Hiding a location update button in settings seems very UX-unfriendly to me.

What I was planning to do was request regular location updates, which will check your location every 15 minutes while the app is open.

**Comment by soren121** [comment]
This should be fixed in version 1.3.0.0, although I haven't tested it extensively.
